.Dd August 15, 2014
.Dt INTRCTL 8
.Os
.Sh NAME
.Nm intrctl
.Nd program to control interrupts
.Sh SYNOPSIS
.Nm intrctl
.Ar command
.Op Ar options
.Sh DESCRIPTION
The
.Nm
command can be used to control and inspect the state of intrerupts in the system.

.Ed
.Sh SEE ALSO
.Xr cpuctl 8

.Sh HISTORY
The
.Nm
command first appeared in
.Nx X.X .
