.Dd August 19, 2014
.Dt INTRCTL 8
.Os
.Sh NAME
.Nm intrctl
.Nd program to control interrupts
.Sh SYNOPSIS
.Nm intrctl
.Ar command
.Op Ar options
.Sh DESCRIPTION
The
.Nm
command can be used to control and inspect the state of intrerupts in the system.
.Pp
The first argument,
.Ar command ,
specifies the action to take.
Valid commands are:
.Bl -tag -width XofflineXcpunoX
.It list
for each IRQ in the system, display interrupt counts per CPU.
.It affinity Fl c Ar cpuid Fl i Ar irq
set affinity
.Ar irq
interrupt to
.Ar cpuid.
.It intr Fl c Ar cpuid
enable interrupts to set affinity to
.Ar cpuid.
.It nointr Fl c Ar cpuid
disable interrupts to set affinity to
.Ar cpuid.
.El
.Sh FILES
.Bl -tag -width /dev/intrctl -compact
.It Pa /dev/intrctl
control interrupt
.Ed
.Sh SEE ALSO
.Xr cpuctl 8
.Sh HISTORY
The
.Nm
command first appeared in
.Nx X.X .
